import { useRouter } from 'next/router'
import Head from 'next/head'
import MuxPlayer from '@mux/mux-player-react'
import useSWR from 'swr'

const fetcher = (url:string) => fetch(url).then((res) => res.json());
const title = process.env.NEXT_PUBLIC_Title

const Post = () => {
    const router = useRouter()
    const { pid } = router.query
    const assetId = pid as string

    const {data, error} = useSWR(
        "/api/live?id=" + assetId,
        fetcher
    )

    const date = data?new Date(data.dateTime):null
    const localisedDate = ((date)?date.toLocaleString('en-AU'): null)

    return (
        <>
          <Head>
            <title>{title}</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
            <script defer src="https://www.gstatic.com/cv/js/sender/v1/cast_sender.js?loadCastFramework=1"></script>
          </Head>
          <div className="navbar bg-base-100">
            <h1 className="text-xl">{title}</h1>
          </div>
          <article className='container mx-auto'>
            <p className='text-center'>{data?'This was the service for ' + data.name + '. This service started ' + localisedDate + '.':'VOD not found'}</p>
            <MuxPlayer 
                playbackId={assetId}
            />
          </article>
          <footer className="footer footer-center p-4 bg-base-300 text-base-content">
            <div>
              <p>Copyright © 2023 - All right reserved by ACME Industries Ltd</p>
            </div>
          </footer>
        </>
      )
  }

  export default Post
