import Head from 'next/head'
import { Inter } from '@next/font/google'
import MuxPlayer from '@mux/mux-player-react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="navbar bg-base-100">
        <a className="btn btn-ghost normal-case text-xl">Sessions Funerals</a>
      </div>
      <article className='container mx-auto'>
        <p className='text-center'>Hello</p>
        <MuxPlayer />
        <p className='text-center'>Hello</p>
      </article>
      <footer className="footer footer-center p-4 bg-base-300 text-base-content">
        <div>
          <p>Copyright © 2023 - All right reserved by ACME Industries Ltd</p>
        </div>
      </footer>
    </>
  )
}
