import Head from 'next/head'
import MuxPlayer from '@mux/mux-player-react'
import useSWR from 'swr'
import Script from 'next/script';

function fetcher(url: string) {
	return fetch(url).then((res) => res.json());
}
const title = process.env.NEXT_PUBLIC_Title
const businessName = process.env.NEXT_PUBLIC_Footer

export default function Index(): JSX.Element {

	const { data } = useSWR(
		process.env.NEXT_PUBLIC_API_URL + "live",
		fetcher
	);

	const date = data ? new Date(data.dateTime) : null;
	const localisedDate = ((date) ? date.toLocaleString('en-AU') : null);
	const year = new Date().getFullYear();

	return (
		<>
			<Script defer src="https://www.gstatic.com/cv/js/sender/v1/cast_sender.js?loadCastFramework=1"></Script>
			<Head>
				<title>{title}</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="navbar bg-base-100">
				<h1 className="text-xl">{title}</h1>
			</div>
			<article className='container mx-auto'>
				<p className='text-center'>{data ? (data.funeral?`This is the service for ${data.name}. This service starts ${localisedDate}.`: 'There is no livestreamed funerals scheduled at this time.') : 'Fetching Data!!!'}</p>
				<MuxPlayer
					playbackId={data ? (data.funeral?data.liveId:'') : ''}
					streamType='live'   
				/>
			</article>
			<footer className="footer footer-center p-4 bg-base-300 text-base-content">
				<div>
					<p>{`Copyright © ${year} - All right reserved by ${businessName}`}</p>
				</div>
			</footer>
		</>
	);
}