import Head from 'next/head'
import MuxPlayer from '@mux/mux-player-react'
import useSWR from 'swr'
import { useEffect, useState } from 'react';
import Script from 'next/script';

function fetcher(url: string) {
	return fetch(url).then((res) => res.json());
}
const title = process.env.NEXT_PUBLIC_Title
const businessName = process.env.NEXT_PUBLIC_Footer

export default function VOD(): JSX.Element {
	const [assetId, setAssetId] = useState<string>('');

	useEffect(() => {
		const url = new URL(window.location.href);
		const localAssetId = url.searchParams.get('id');
		setAssetId(localAssetId as string);
	}, [setAssetId]);

	const { data, error } = useSWR(
		process.env.NEXT_PUBLIC_API_URL + assetId,
		fetcher
	);

	const date = data ? new Date(data.dateTime) : null;
	const localisedDate = ((date) ? date.toLocaleString('en-AU') : null);
	const year = new Date().getFullYear();

	return (
		<>
			<Script defer src="https://www.gstatic.com/cv/js/sender/v1/cast_sender.js?loadCastFramework=1"></Script>
			<Head>
				<title>{title}</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="navbar bg-base-100">
				<h1 className="text-xl">{title}</h1>
			</div>
			<article className='container mx-auto'>
				<p className='text-center'>{data ? `This was the service for ${data.name}. This service started ${localisedDate}.` : 'VOD not found'}</p>
				<MuxPlayer
					playbackId={data ? data.assetId : ''}
					startTime={data ? (data.startTime ? data.startTime : 0) : 0}
					streamType='on-demand'   
				/>
			</article>
			<footer className="footer footer-center p-4 bg-base-300 text-base-content">
				<div>
					<p>{`Copyright © ${year} - All right reserved by ${businessName}`}</p>
				</div>
			</footer>
		</>
	);
}